{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}svc
  labels:
    app: {{ .Values.database.labels }}
    helm.sh/chart: {{ .Chart.Version | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
      protocol: TCP
      name: {{ .Values.database.name }}-port
  selector:
      app: {{ .Values.database.selectorLabels }}
{{- end }}