{{- if .Values.database.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.database.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.database.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.database.labels }}
    helm.sh/chart: {{ .Chart.Version | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  name: {{ .Values.database.name }}-pvc
spec:
  accessModes:
{{ toYaml .Values.database.persistentVolume.accessModes | indent 4 }}
{{- if .Values.database.persistentVolume.storageClass }}
{{- if (eq "-" .Values.database.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.database.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.database.persistentVolume.volumeBindingMode }}
  volumeBindingModeName: "{{ .Values.database.persistentVolume.volumeBindingMode }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.database.persistentVolume.size }}"
{{- end -}}
