{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secrets }}-env-secrets
  labels:
    app: {{ .Values.database.labels }}
    helm.sh/chart: {{ .Chart.Version | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}

type: Opaque
data:
  mysql_database: {{ .Values.database.mysql_database | b64enc }}
  mysql_password: {{ .Values.database.mysql_password | b64enc }}
  mysql_random_root_password: {{ .Values.database.mysql_random_root_password | b64enc }}
  mysql_user: {{ .Values.database.mysql_user | b64enc }}
{{- end }}